source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails', '4.2.4'
gem 'pg'
gem 'active_model_serializers'

# gem 'unicorn'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'stringex'

group :development, :test do
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

